[project]
name = "draft-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "rapidfuzz>=3.14.6",
    "streamlit>=1.63.0",
    "streamlit-autorefresh>=1.0.1",
]

[project.scripts]
draft-assistant = "draft_assistant:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
